### ISSUE TITLE
Develop a REST API from R Shiny

### ISSUE THREAD

**Issue by bastianilso** [med-material/web-dashboard-virtual-agent#2]
We need to develop some sort of communication between R Shiny and Rasa.

The use case: Rasa will need to know what part of the website, R Shiny is current at. Therefore, we need to an ID of the current page in R Shiny to Rasa, through a REST API.

The API could like the following - having a "pageID" that can  be accessed on a URL.
![image](https://user-images.githubusercontent.com/3967945/193566565-3c7bb9ec-5d1a-47a9-8822-f2e906e8ac8b.png)

To understand how we can create a REST API like that there are some steps to do:
- First, investigate how a REST API is "normally" created for websites. Just to give initial introduction to the idea behind REST APIs, why they are there, what they are good for.

- We can use the plumber library to create a REST API in R. As a starting point, create a REST API by running the examples from here:
https://www.rplumber.io/

- Once the example is working, we can try to fetch the data from python. See an example of how to do this, here:
https://github.com/bastianilso/ink-weatherstation/blob/8a08b47f8bcdc05753248f4cf3b273369c42cd71/lib/weather.py#L39

- After this, we should modify the example so that it returns a "pageID" which is a string stored in the R script.

- Finally, we should try to include the plumber calls into an R shiny app and send some data, fx. `input$bin`. or it could be that you create some `tabPanel` in the ui function and read which tab is currently open.

**Comment by bastianilso** [comment]
Hi @Andy31700 , feel free to upload the code you have for making a REST API with R and plumber. I can take a look and provide feedback, if you need it.

**Comment by Andy31700** [comment]
Hello @bastianilso, I manage to send parameters to use the REST API functions in R with my python program. I just published it in the repositories.

**Comment by bastianilso** [comment]
Great @Andy31700, I think we should close this issue then and I will create separate issues for developing features within this R shiny REST API.
